Repository Zendro-dev/single-page-app, pull requests merged in 2021-05, with the labels that each got.

#61 dependencies: update cycle 2021 05 04
  cypress/integration/login-form.test.ts
  package.json
  src/components/inputs/select-input.tsx
  src/pages/index.tsx
  yarn.lock
Labels: dependencies

#62 feat: theme colors and navigation UX
  src/components/navigation/breadcrumbs.tsx
  src/components/toolbar/lang-switcher.tsx
  src/components/toolbar/logout-button.tsx
  src/layouts/models/layout.tsx
  src/layouts/models/main.tsx
  src/layouts/models/navigation.tsx
  src/layouts/models/toolbar.tsx
  src/styles/theme.ts
  src/zendro/record-form/form.tsx
  theme.d.ts
Labels: bug, enhancement

#65 feat: model permissions
  src/hooks/index.ts
  src/hooks/usePermissions.tsx
  src/layouts/models/navigation.tsx
  src/layouts/models/restricted.tsx
  src/pages/[group]/[model]/details.tsx
  src/pages/[group]/[model]/edit.tsx
  src/pages/[group]/[model]/new.tsx
  src/styles/theme.ts
  theme.d.ts
  tsconfig.json
  typings/theme.d.ts
Labels: enhancement

#66 feat: I18n translations
  src/components/forms/login-form.tsx
  src/components/forms/password-field.tsx
  src/components/toolbar/lang-switcher.tsx
  src/components/toolbar/logout-button.tsx
  src/i18n/de.js
  src/i18n/de.json
  src/i18n/en.js
  src/i18n/en.json
  src/i18n/es.js
  src/i18n/es.json
  src/i18n/index.ts
  src/i18n/react-i18next.d.ts
  src/layouts/models/main.tsx
  src/layouts/models/model-info.tsx
  src/layouts/models/navigation.tsx
  src/layouts/models/restricted.tsx
  src/pages/[group]/[model]/details.tsx
  src/pages/[group]/[model]/edit.tsx
  src/pages/[group]/[model]/index.tsx
  src/pages/[group]/[model]/new.tsx
  src/pages/index.tsx
  src/zendro/associations-table/table.tsx
  src/zendro/model-table/table-header.tsx
  src/zendro/model-table/table-pagination.tsx
  src/zendro/model-table/table-search.tsx
  src/zendro/model-table/table.tsx
  src/zendro/record-fields/array-field.tsx
  src/zendro/record-form/form-field.tsx
  src/zendro/record-form/form-header.tsx
  src/zendro/record-form/form.tsx
Labels: enhancement

#68 fix: expired-revalidated
  src/components/toolbar/login-button.tsx
  src/hooks/useAuth.tsx
  src/i18n/de.json
  src/i18n/en.json
  src/i18n/es.json
  src/layouts/models/model-restricted.tsx
  src/styles/theme.ts
  src/types/auth.ts
  src/utils/auth.ts
Labels: bug, enhancement

#74 fix: move model authorization to pages
  acl2.d.ts
  package.json
  src/build/acl-models.preval.ts
  src/build/routes.preval.ts
  src/build/routes.ts
  src/components/alert-card/alert-card.tsx
  src/components/alert-card/index.ts
  src/components/dynamic/mui-icon.tsx
  src/components/navigation/nav-group.tsx
  src/hooks/index.ts
  src/hooks/useModel.ts
  src/i18n/de.json
  src/i18n/en.json
  src/i18n/es.json
  src/layouts/index.ts
  src/layouts/models/model-layout.tsx
  src/layouts/models/model-main.tsx
  src/layouts/models/model-navigation.tsx
  src/layouts/models/model-restricted.tsx
  src/pages/[group]/[model]/details.tsx
  src/pages/[group]/[model]/edit.tsx
  src/pages/[group]/[model]/index.tsx
  src/pages/[group]/[model]/new.tsx
  src/pages/[group]/index.tsx
  src/types/elements.ts
  src/types/errors.ts
  src/types/routes.ts
  src/utils/acl.ts
  src/utils/auth.ts
  src/utils/errors.ts
  src/utils/router.ts
  src/zendro/associations-table/table.tsx
  src/zendro/model-bouncer/index.ts
  src/zendro/model-bouncer/model-bouncer.tsx
  tsconfig.json
  yarn.lock
Labels: bug, enhancement

#75 styles: record-page ux and styles
  src/pages/[group]/[model]/details.tsx
  src/pages/[group]/[model]/edit.tsx
  src/pages/[group]/[model]/new.tsx
  src/zendro/record-form/form-header.tsx
  src/zendro/record-form/form.tsx
Labels: enhancement

#77 fix: Untwist fixes merge
  src/build/acl-models.preval.ts
  src/build/queries.preval.ts
  src/build/queries.ts
  src/build/routes.preval.ts
  src/components/select-input/select-input.tsx
  src/utils/queries.ts
  src/zendro/associations-table/table.tsx
Labels: bug, enhancement

#79 feat: codegen queries as typescript
  src/build/queries.preval.ts
Labels: enhancement

#80 fix: auth-based permissions
  src/hooks/useModel.ts
  src/utils/acl.ts
Labels: bug

#81 feat: style and format fixes
  src/layouts/app/app-layout.tsx
  src/layouts/models/model-layout.tsx
  src/layouts/models/model-main.tsx
  src/pages/[group]/[model]/details.tsx
  src/pages/[group]/[model]/edit.tsx
  src/pages/[group]/[model]/index.tsx
  src/pages/[group]/[model]/new.tsx
  src/pages/index.tsx
  src/zendro/model-table/table-body.tsx
  src/zendro/model-table/table.tsx
  src/zendro/record-form/form-utils.ts
  src/zendro/record-form/form.tsx
Labels: bug, enhancement

#82 refactor: support recursive DataRecord interface
  src/types/models.ts
  src/zendro/model-table/hooks/useRecords.tsx
Labels: enhancement

#83 hotfix: app homepage is not responsive
  src/pages/index.tsx
Labels: bug, enhancement

#84 hotfix: int value error when searching with whitespace
  src/utils/validation.ts
Labels: bug
