Repository Zendro-dev/single-page-app, pull requests merged in 2021-06, with the labels that each got.

#85 fix: csv download not authorized
  src/pages/[group]/[model]/index.tsx
  src/utils/browser.ts
Labels: bug, enhancement

#86 feat: E2e tests
  .gitignore
  cypress.json
  cypress/e2e/details.test.ts
  cypress/e2e/edit.test.ts
  cypress/e2e/login-form.test.ts
  cypress/e2e/model-page.test.ts
  cypress/e2e/new.test.ts
  cypress/fixtures/example.json
  cypress/integration/login-form.test.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  package.json
  src/components/dialog-popup/dialog-popup.tsx
  src/components/login-form/login-button.tsx
  src/components/select-input/select-input.tsx
  src/i18n/de.json
  src/i18n/en.json
  src/i18n/es.json
  src/layouts/app/app-layout.tsx
  src/pages/[group]/[model]/details.tsx
  src/pages/[group]/[model]/edit.tsx
  src/pages/[group]/[model]/index.tsx
  src/pages/index.tsx
  src/store/index.ts
  src/zendro/associations-table/table.tsx
  src/zendro/model-table/hooks/usePagination.tsx
  src/zendro/model-table/table-body.tsx
  src/zendro/model-table/table-column.tsx
  src/zendro/model-table/table-header.tsx
  src/zendro/model-table/table-pagination.tsx
  src/zendro/model-table/table-search.tsx
  src/zendro/record-fields/array-field.tsx
  src/zendro/record-form/form-field.tsx
  src/zendro/record-form/form.tsx
  test/config/.env
  test/config/docker-compose-test.yml
  test/config/patches/country.patch
  test/testenv_sync.sh
  yarn.lock
Labels: enhancement

#87 feat: record association page
  cypress/e2e/association-page.test.ts
  cypress/e2e/attributes-page.test.ts
  cypress/e2e/details.test.ts
  cypress/e2e/login-form.test.ts
  cypress/e2e/model-page.test.ts
  cypress/e2e/new.test.ts
  src/build/acl-models.preval.ts
  src/build/routes.preval.ts
  src/build/routes.ts
  src/components/alert-card/alert-card.tsx
  src/components/nav-tabs/index.tsx
  src/components/nav-tabs/nav-tabs.tsx
  src/components/nav-tabs/tab-menu.tsx
  src/layouts/models/model-layout.tsx
  src/layouts/models/model-main.tsx
  src/layouts/models/model-navigation.tsx
  src/pages/[group]/[model]/[request]/[association]/index.tsx
  src/pages/[group]/[model]/[request]/index.tsx
  src/pages/[group]/[model]/details.tsx
  src/pages/[group]/[model]/new.tsx
  src/types/routes.ts
  src/utils/router.ts
  src/zendro/associations-table/index.ts
  src/zendro/associations-table/table.tsx
  src/zendro/record-form/form.tsx
Labels: enhancement

#89 refactor: association types.
  admin/role.json
  admin/user.json
  models/capital.json
  models/continent.json
  models/country.json
  models/river.json
  src/build/models.ts
  src/build/queries.ts
  src/pages/[group]/[model]/[request]/[association]/index.tsx
  src/types/models.ts
  src/utils/models.ts
  src/utils/queries.ts
Labels: refactor

#90 refactor: assoc types #2
  models/capital.json
  models/continent.json
  models/country.json
  models/river.json
  src/types/models.ts
  src/utils/models.ts
Labels: refactor

#92 feat: storage type routes
  src/build/models.preval.ts
  src/build/models.ts
  src/build/queries.ts
  src/build/routes.ts
  src/hooks/useModel.ts
  src/pages/[group]/[model]/[request]/[association]/index.tsx
  src/pages/[group]/[model]/[request]/index.tsx
  src/pages/[group]/[model]/index.tsx
  src/types/models.ts
  src/utils/models.ts
Labels: enhancement
