Repository Zendro-dev/single-page-app, pull requests merged in 2021-03, with the labels that each got.

#41 feat: record detail
  .eslintrc.js
  admin/role.json
  package.json
  src/components/association-list/index.ts
  src/components/association-list/list-link-item.tsx
  src/components/association-list/list-link.tsx
  src/components/association-list/list.tsx
  src/components/attributes-form/form-actions.tsx
  src/components/attributes-form/form.tsx
  src/components/attributes-form/index.ts
  src/components/buttons/fab.tsx
  src/components/forms/attribute-form.tsx
  src/components/input/attribute-field.tsx
  src/components/input/base-field.tsx
  src/components/input/bool-field.tsx
  src/components/input/datetime-field.tsx
  src/components/input/float-field.tsx
  src/components/input/index.tsx
  src/components/input/input-container.tsx
  src/components/input/int-field.tsx
  src/components/input/string-field.tsx
  src/components/links/fab-link.tsx
  src/components/links/index.tsx
  src/pages/[model]/item.tsx
  src/types/models.ts
  src/types/queries.ts
  src/types/requests.ts
  src/utils/inflection.ts
  src/utils/models.ts
  src/utils/queries.ts
  src/utils/requests.ts
  src/utils/validation.ts
  yarn.lock
Labels: enhancement

#42 feat: Table toolbar
  src/components/buttons/icon-button.jsx
  src/components/records-table/download-menu.jsx
  src/components/records-table/index.js
  src/components/records-table/search-field.jsx
  src/components/records-table/table-toolbar.jsx
  src/components/records-table/upload-dialog.jsx
  src/types/queries.ts
  src/utils/queries.ts
  src/utils/requests.ts
  src/utils/tableToolBar.js
Labels: enhancement

#45 feat: Table errors
  package.json
  src/components/alert/snackbar.jsx
  src/components/alert/snackbar.tsx
  src/components/records-table/table-row.tsx
  src/components/records-table/table-toolbar-download-menu.jsx
  src/components/records-table/table-toolbar-upload-dialog.jsx
  src/components/records-table/table.tsx
  src/hooks/useToastNotification.tsx
  src/pages/[model]/item.tsx
  src/pages/_app.tsx
  src/pages/login.tsx
  src/types/models.ts
  src/types/queries.ts
  src/types/requests.ts
  src/utils/requests.ts
  yarn.lock
Labels: enhancement

#47 Use dialog hook
  src/components/dialog/dialog-context.ts
  src/components/dialog/dialog-provider.tsx
  src/components/records-table/table-head-cell.tsx
  src/components/records-table/table.tsx
  src/hooks/useDialog.tsx
  src/pages/[model]/item.tsx
  src/pages/_app.tsx
  src/types/dialog.ts
Labels: enhancement

#48 refactor: separate confirmation-dialog from useDialog
  src/components/dialog/confirmation-dialog.tsx
  src/components/dialog/dialog-context.ts
  src/components/dialog/dialog-provider.tsx
  src/hooks/useDialog.tsx
  src/pages/_app.tsx
  src/types/dialog.ts
Labels: enhancement

#51 feat: shared layouts
  src/components/placeholders/restricted-resource.tsx
  src/layouts/index.ts
  src/layouts/models/layout.tsx
  src/layouts/models/navigation.tsx
  src/layouts/models/toolbar.tsx
  src/pages/[model]/index.tsx
  src/pages/[model]/item.tsx
  src/pages/_app.tsx
Labels: enhancement

#53 feat: Cypress E2E testing setup
  .gitignore
  README.md
  babel.config.js
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/login-form.test.ts
  cypress/plugins/index.js
  cypress/support/commands.ts
  cypress/support/index.d.ts
  cypress/support/index.js
  jest.config.js
  package.json
  src/components/attributes-form/form-errors.tsx
  src/components/forms/login-form.tsx
  test/config/Dockerfile.graphql_server
  test/config/Dockerfile.postgres
  test/config/data_models_storage_config1.json
  test/config/data_models_storage_config2.json
  test/config/docker-compose-test.yml
  test/config/initUserDb.sh
  test/config/integration-test.sql
  test/config/migrateDbAndStartServer.sh
  test/models/server1/alien.json
  test/models/server1/capital.json
  test/models/server1/continent.json
  test/models/server1/country.json
  test/models/server1/river.json
  test/testenv_cli.man
  test/testenv_cli.sh
  test/testenv_constants.sh
  test/testenv_docker_up.sh
  test/testenv_generate_code.sh
  test/testenv_init_run_env.sh
  test/testenv_remove.sh
  test/testenv_sync.sh
  tsconfig.json
  yarn.lock
Labels: enhancement

#54 refactor: restricted models
  src/build/routes.js
  src/components/accordion/index.ts
  src/components/accordion/item.tsx
  src/components/containers/accordion.tsx
  src/components/containers/index.ts
  src/components/placeholders/restricted-resource.tsx
  src/components/records-table/table.tsx
  src/hooks/index.ts
  src/hooks/useAuth.tsx
  src/hooks/useCountdown.tsx
  src/hooks/useModel.tsx
  src/hooks/useRedirect.tsx
  src/layouts/models/layout.tsx
  src/layouts/models/main.tsx
  src/layouts/models/model-info.tsx
  src/layouts/models/navigation.tsx
  src/layouts/models/restricted.tsx
  src/pages/[group]/[model]/details.tsx
  src/pages/[group]/[model]/edit.tsx
  src/pages/[group]/[model]/index.tsx
  src/pages/[group]/[model]/new.tsx
  src/pages/[group]/index.tsx
  src/pages/home.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/store/auth-slice.ts
  src/types/models.ts
  src/types/routes.ts
  src/utils/models.ts
  src/utils/router.ts
  src/utils/static.ts
  src/utils/validation.ts
Labels: enhancement

#55 feat: Table components use zendro client + typescript port
  src/components/buttons/icon-button.jsx
  src/components/buttons/icon-button.tsx
  src/components/records-table/table-pagination.tsx
  src/components/records-table/table-toolbar-download-menu.tsx
  src/components/records-table/table-toolbar-search-field.tsx
  src/components/records-table/table-toolbar-upload-dialog.tsx
  src/components/records-table/table-toolbar.tsx
  src/components/records-table/table.tsx
  src/types/queries.ts
Labels: enhancement

#56 chore: upgrade deps
  .eslintrc.js
  .husky/.gitignore
  package.json
  yarn.lock
Labels: dependencies

#57 hotfix: action routes
  src/components/records-table/table.tsx
  src/hooks/useModel.tsx
  src/pages/[group]/[model]/details.tsx
  src/pages/[group]/[model]/edit.tsx
  src/pages/[group]/[model]/new.tsx
  src/types/acl.ts
Labels: bug
